//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareerCloud.UnitTests.Assignment5.SystemService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SystemService.ISystem")]
    public interface ISystem {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystem/AddSystemCountryCode", ReplyAction="http://tempuri.org/ISystem/AddSystemCountryCodeResponse")]
        void AddSystemCountryCode(CareerCloud.Pocos.SystemCountryCodePoco[] item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystem/AddSystemCountryCode", ReplyAction="http://tempuri.org/ISystem/AddSystemCountryCodeResponse")]
        System.Threading.Tasks.Task AddSystemCountryCodeAsync(CareerCloud.Pocos.SystemCountryCodePoco[] item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystem/GetAllSystemCountryCode", ReplyAction="http://tempuri.org/ISystem/GetAllSystemCountryCodeResponse")]
        CareerCloud.Pocos.SystemCountryCodePoco[] GetAllSystemCountryCode();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystem/GetAllSystemCountryCode", ReplyAction="http://tempuri.org/ISystem/GetAllSystemCountryCodeResponse")]
        System.Threading.Tasks.Task<CareerCloud.Pocos.SystemCountryCodePoco[]> GetAllSystemCountryCodeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystem/GetSingleSystemCountryCode", ReplyAction="http://tempuri.org/ISystem/GetSingleSystemCountryCodeResponse")]
        CareerCloud.Pocos.SystemCountryCodePoco GetSingleSystemCountryCode(string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystem/GetSingleSystemCountryCode", ReplyAction="http://tempuri.org/ISystem/GetSingleSystemCountryCodeResponse")]
        System.Threading.Tasks.Task<CareerCloud.Pocos.SystemCountryCodePoco> GetSingleSystemCountryCodeAsync(string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystem/RemoveSystemCountryCode", ReplyAction="http://tempuri.org/ISystem/RemoveSystemCountryCodeResponse")]
        void RemoveSystemCountryCode(CareerCloud.Pocos.SystemCountryCodePoco[] item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystem/RemoveSystemCountryCode", ReplyAction="http://tempuri.org/ISystem/RemoveSystemCountryCodeResponse")]
        System.Threading.Tasks.Task RemoveSystemCountryCodeAsync(CareerCloud.Pocos.SystemCountryCodePoco[] item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystem/UpdateSystemCountryCode", ReplyAction="http://tempuri.org/ISystem/UpdateSystemCountryCodeResponse")]
        void UpdateSystemCountryCode(CareerCloud.Pocos.SystemCountryCodePoco[] item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystem/UpdateSystemCountryCode", ReplyAction="http://tempuri.org/ISystem/UpdateSystemCountryCodeResponse")]
        System.Threading.Tasks.Task UpdateSystemCountryCodeAsync(CareerCloud.Pocos.SystemCountryCodePoco[] item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystem/AddSystemLanguageCode", ReplyAction="http://tempuri.org/ISystem/AddSystemLanguageCodeResponse")]
        void AddSystemLanguageCode(CareerCloud.Pocos.SystemLanguageCodePoco[] item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystem/AddSystemLanguageCode", ReplyAction="http://tempuri.org/ISystem/AddSystemLanguageCodeResponse")]
        System.Threading.Tasks.Task AddSystemLanguageCodeAsync(CareerCloud.Pocos.SystemLanguageCodePoco[] item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystem/GetAllSystemLanguageCode", ReplyAction="http://tempuri.org/ISystem/GetAllSystemLanguageCodeResponse")]
        CareerCloud.Pocos.SystemLanguageCodePoco[] GetAllSystemLanguageCode();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystem/GetAllSystemLanguageCode", ReplyAction="http://tempuri.org/ISystem/GetAllSystemLanguageCodeResponse")]
        System.Threading.Tasks.Task<CareerCloud.Pocos.SystemLanguageCodePoco[]> GetAllSystemLanguageCodeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystem/GetSingleSystemLanguageCode", ReplyAction="http://tempuri.org/ISystem/GetSingleSystemLanguageCodeResponse")]
        CareerCloud.Pocos.SystemLanguageCodePoco GetSingleSystemLanguageCode(string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystem/GetSingleSystemLanguageCode", ReplyAction="http://tempuri.org/ISystem/GetSingleSystemLanguageCodeResponse")]
        System.Threading.Tasks.Task<CareerCloud.Pocos.SystemLanguageCodePoco> GetSingleSystemLanguageCodeAsync(string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystem/RemoveSystemLanguageCode", ReplyAction="http://tempuri.org/ISystem/RemoveSystemLanguageCodeResponse")]
        void RemoveSystemLanguageCode(CareerCloud.Pocos.SystemLanguageCodePoco[] item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystem/RemoveSystemLanguageCode", ReplyAction="http://tempuri.org/ISystem/RemoveSystemLanguageCodeResponse")]
        System.Threading.Tasks.Task RemoveSystemLanguageCodeAsync(CareerCloud.Pocos.SystemLanguageCodePoco[] item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystem/UpdateSystemLanguageCode", ReplyAction="http://tempuri.org/ISystem/UpdateSystemLanguageCodeResponse")]
        void UpdateSystemLanguageCode(CareerCloud.Pocos.SystemLanguageCodePoco[] item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystem/UpdateSystemLanguageCode", ReplyAction="http://tempuri.org/ISystem/UpdateSystemLanguageCodeResponse")]
        System.Threading.Tasks.Task UpdateSystemLanguageCodeAsync(CareerCloud.Pocos.SystemLanguageCodePoco[] item);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISystemChannel : CareerCloud.UnitTests.Assignment5.SystemService.ISystem, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SystemClient : System.ServiceModel.ClientBase<CareerCloud.UnitTests.Assignment5.SystemService.ISystem>, CareerCloud.UnitTests.Assignment5.SystemService.ISystem {
        
        public SystemClient() {
        }
        
        public SystemClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SystemClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SystemClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SystemClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddSystemCountryCode(CareerCloud.Pocos.SystemCountryCodePoco[] item) {
            base.Channel.AddSystemCountryCode(item);
        }
        
        public System.Threading.Tasks.Task AddSystemCountryCodeAsync(CareerCloud.Pocos.SystemCountryCodePoco[] item) {
            return base.Channel.AddSystemCountryCodeAsync(item);
        }
        
        public CareerCloud.Pocos.SystemCountryCodePoco[] GetAllSystemCountryCode() {
            return base.Channel.GetAllSystemCountryCode();
        }
        
        public System.Threading.Tasks.Task<CareerCloud.Pocos.SystemCountryCodePoco[]> GetAllSystemCountryCodeAsync() {
            return base.Channel.GetAllSystemCountryCodeAsync();
        }
        
        public CareerCloud.Pocos.SystemCountryCodePoco GetSingleSystemCountryCode(string code) {
            return base.Channel.GetSingleSystemCountryCode(code);
        }
        
        public System.Threading.Tasks.Task<CareerCloud.Pocos.SystemCountryCodePoco> GetSingleSystemCountryCodeAsync(string code) {
            return base.Channel.GetSingleSystemCountryCodeAsync(code);
        }
        
        public void RemoveSystemCountryCode(CareerCloud.Pocos.SystemCountryCodePoco[] item) {
            base.Channel.RemoveSystemCountryCode(item);
        }
        
        public System.Threading.Tasks.Task RemoveSystemCountryCodeAsync(CareerCloud.Pocos.SystemCountryCodePoco[] item) {
            return base.Channel.RemoveSystemCountryCodeAsync(item);
        }
        
        public void UpdateSystemCountryCode(CareerCloud.Pocos.SystemCountryCodePoco[] item) {
            base.Channel.UpdateSystemCountryCode(item);
        }
        
        public System.Threading.Tasks.Task UpdateSystemCountryCodeAsync(CareerCloud.Pocos.SystemCountryCodePoco[] item) {
            return base.Channel.UpdateSystemCountryCodeAsync(item);
        }
        
        public void AddSystemLanguageCode(CareerCloud.Pocos.SystemLanguageCodePoco[] item) {
            base.Channel.AddSystemLanguageCode(item);
        }
        
        public System.Threading.Tasks.Task AddSystemLanguageCodeAsync(CareerCloud.Pocos.SystemLanguageCodePoco[] item) {
            return base.Channel.AddSystemLanguageCodeAsync(item);
        }
        
        public CareerCloud.Pocos.SystemLanguageCodePoco[] GetAllSystemLanguageCode() {
            return base.Channel.GetAllSystemLanguageCode();
        }
        
        public System.Threading.Tasks.Task<CareerCloud.Pocos.SystemLanguageCodePoco[]> GetAllSystemLanguageCodeAsync() {
            return base.Channel.GetAllSystemLanguageCodeAsync();
        }
        
        public CareerCloud.Pocos.SystemLanguageCodePoco GetSingleSystemLanguageCode(string code) {
            return base.Channel.GetSingleSystemLanguageCode(code);
        }
        
        public System.Threading.Tasks.Task<CareerCloud.Pocos.SystemLanguageCodePoco> GetSingleSystemLanguageCodeAsync(string code) {
            return base.Channel.GetSingleSystemLanguageCodeAsync(code);
        }
        
        public void RemoveSystemLanguageCode(CareerCloud.Pocos.SystemLanguageCodePoco[] item) {
            base.Channel.RemoveSystemLanguageCode(item);
        }
        
        public System.Threading.Tasks.Task RemoveSystemLanguageCodeAsync(CareerCloud.Pocos.SystemLanguageCodePoco[] item) {
            return base.Channel.RemoveSystemLanguageCodeAsync(item);
        }
        
        public void UpdateSystemLanguageCode(CareerCloud.Pocos.SystemLanguageCodePoco[] item) {
            base.Channel.UpdateSystemLanguageCode(item);
        }
        
        public System.Threading.Tasks.Task UpdateSystemLanguageCodeAsync(CareerCloud.Pocos.SystemLanguageCodePoco[] item) {
            return base.Channel.UpdateSystemLanguageCodeAsync(item);
        }
    }
}
